conjugate/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('tracker.urls')),
    url('^', include('django.contrib.auth.urls')),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
]

tracker/urls.py
from django.conf.urls import include, url
from django.http import HttpResponseRedirect, HttpResponse

from . import views
app_name = "tracker"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^accounts/',  include('registration.backends.hmac.urls')),
    url(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /",
                                                content_type="text/plain")),
    url(r'^squat_movement/(?P<pk>[0-9]+)/$',
        views.SquatDetailView.as_view(), name='squat_detail'),
    url(r'^deadlift_movement/(?P<pk>[0-9]+)/$',
        views.DeadliftDetailView.as_view(), name='deadlift_detail'),
    url(r'^bench_movement/(?P<pk>[0-9]+)/$',
        views.BenchDetailView.as_view(), name='bench_detail'),
    url(r'^lower_movement/(?P<pk>[0-9]+)/$',
        views.LowerDetailView.as_view(), name='lower_detail'),
    url(r'^upper_movement/(?P<pk>[0-9]+)/$',
        views.UpperDetailView.as_view(), name='upper_detail'),
    url(r'^squat_movement/new$', views.new_squat, name='squat_new'),
    url(r'^deadlift_movement/new$', views.new_deadlift, name='deadlift_new'),
    url(r'^bench_movement/new$', views.new_bench, name='bench_new'),
    url(r'^lower_movement/new$', views.new_lower, name='lower_new'),
    url(r'^upper_movement/new$', views.new_upper, name='upper_new'),
    url(r'^squat_movement/(?P<pk>\d+)/edit/$',
        views.squat_edit, name='squat_edit'),
    url(r'^bench_movement/(?P<pk>\d+)/edit/$',
        views.bench_edit, name='bench_edit'),
    url(r'^deadlift_movement/(?P<pk>\d+)/edit/$',
        views.deadlift_edit, name='deadlift_edit'),
    url(r'^upper_movement/(?P<pk>\d+)/edit/$',
        views.upper_edit, name='upper_edit'),
    url(r'^lower_movement/(?P<pk>\d+)/edit/$',
        views.lower_edit, name='lower_edit'),
    url(r'^squat_movement/search$', views.squat_search, name='squat_search'),
    url(r'^bench_movement/search$', views.bench_search, name='bench_search'),
    url(r'^deadlift_movement/search$',
        views.deadlift_search, name='deadlift_search'),
    url(r'^upper_movement/search$', views.upper_search, name='upper_search'),
    url(r'^lower_movement/search$', views.lower_search, name='lower_search'),
    url(r'^analysis$', views.analysis, name='analysis')
]

tracker/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class SquatMovement(models.Model):
    user = models.ForeignKey('auth.User')
    created_at = models.DateField(default=timezone.now, blank=True)
    effort_type = models.CharField(max_length=60)
    squat_notes = models.CharField(max_length=300, blank=True)
    box_free = models.CharField(max_length=60)
    bar_type = models.CharField(max_length=60, blank=True)
    bands_type = models.CharField(max_length=60, blank=True)
    reverse = models.BooleanField(default=False)
    chain_weight = models.IntegerField(default=0, blank=True)
    movement_weight = models.IntegerField(default=0)
    movement_sets = models.IntegerField(default=0)
    movement_reps = models.IntegerField(default=0)
    media_url = models.URLField(blank=True)


class DeadliftMovement(models.Model):
    user = models.ForeignKey('auth.User')
    created_at = models.DateField(default=timezone.now, blank=True)
    effort_type = models.CharField(max_length=60)
    sumo_conventional = models.CharField(max_length=60)
    deficit = models.BooleanField()
    block = models.BooleanField()
    standard = models.BooleanField()
    pin = models.BooleanField()
    reverse = models.BooleanField()
    bands_type = models.CharField(max_length=60, blank=True)
    chain_weight = models.IntegerField(blank=True)
    movement_weight = models.IntegerField(default=0)
    movement_sets = models.IntegerField(default=0)
    movement_reps = models.IntegerField(default=0)
    deadlift_notes = models.CharField(max_length=60, blank=True)
    media_url = models.URLField(blank=True)


class BenchMovement(models.Model):
    user = models.ForeignKey('auth.User')
    created_at = models.DateField(default=timezone.now, blank=True)
    effort_type = models.CharField(max_length=60)
    bar_type = models.CharField(max_length=60, blank=True)
    floor = models.BooleanField()
    reverse = models.BooleanField()
    board = models.IntegerField(blank=True, default=0)
    manpon = models.BooleanField()
    pin = models.BooleanField()
    bench_notes = models.CharField(max_length=60, blank=True)
    bands_type = models.CharField(max_length=60, blank=True)
    chain_weight = models.IntegerField(blank=True)
    movement_weight = models.IntegerField(default=0)
    movement_sets = models.IntegerField(default=0)
    movement_reps = models.IntegerField(default=0)
    media_url = models.URLField(blank=True)


class UpperAccessoryMovement(models.Model):
    user = models.ForeignKey('auth.User')
    created_at = models.DateField(default=timezone.now, blank=True)
    top_set = models.CharField(max_length=60, blank=True)
    close_grippness = models.CharField(max_length=60, blank=True)
    tate_press = models.CharField(max_length=60, blank=True)
    dips = models.CharField(max_length=60, blank=True)
    rev_db_fly = models.CharField(max_length=60, blank=True)
    windmills = models.CharField(max_length=60, blank=True)
    bamboo_bar = models.CharField(max_length=60, blank=True)
    lat_pulldowns = models.CharField(max_length=60, blank=True)
    lat_pullovers = models.CharField(max_length=60, blank=True)
    pec_dec = models.CharField(max_length=60, blank=True)
    reverse_pec_dec = models.CharField(max_length=60, blank=True)
    t_bar_rows = models.CharField(max_length=60, blank=True)
    chest_supported_rows = models.CharField(max_length=60, blank=True)
    low_rows = models.CharField(max_length=60, blank=True)
    pullups = models.CharField(max_length=60, blank=True)
    pushups = models.CharField(max_length=60, blank=True)
    inverted_row = models.CharField(max_length=60, blank=True)
    face_pulls = models.CharField(max_length=60, blank=True)
    db_rows = models.CharField(max_length=60, blank=True)
    db_press = models.CharField(max_length=60, blank=True)
    pullaparts = models.CharField(max_length=60, blank=True)
    tri_extensions = models.CharField(max_length=60, blank=True)
    skull_crushers = models.CharField(max_length=60, blank=True)
    jam_press = models.CharField(max_length=60, blank=True)
    olt_press = models.CharField(max_length=60, blank=True)
    db_rollbacks = models.CharField(max_length=60, blank=True)
    dead_press = models.CharField(max_length=60, blank=True)
    ab_movement = models.CharField(max_length=60, blank=True)
    other = models.CharField(max_length=60, blank=True)
    notes = models.CharField(max_length=300, blank=True)
    media_url = models.URLField(blank=True)


class LowerAccessoryMovement(models.Model):
    user = models.ForeignKey('auth.User')
    created_at = models.DateField(default=timezone.now, blank=True)
    top_set = models.CharField(max_length=60, blank=True)
    chair_dl = models.CharField(max_length=60, blank=True)
    ghr = models.CharField(max_length=60, blank=True)
    lunge = models.CharField(max_length=60, blank=True)
    dimel_dl = models.CharField(max_length=60, blank=True)
    reverse_hyper = models.CharField(max_length=60, blank=True)
    hip_bridge = models.CharField(max_length=60, blank=True)
    good_morning = models.CharField(max_length=60, blank=True)
    step_up = models.CharField(max_length=60, blank=True)
    belt_squat = models.CharField(max_length=60, blank=True)
    hack_squat = models.CharField(max_length=60, blank=True)
    leg_press = models.CharField(max_length=60, blank=True)
    leg_curl = models.CharField(max_length=60, blank=True)
    kb_swings = models.CharField(max_length=60, blank=True)
    trapbar_deadlift = models.CharField(max_length=60, blank=True)
    stiff_leg_dl = models.CharField(max_length=60, blank=True)
    inverse_curl = models.CharField(max_length=60, blank=True)
    front_squat = models.CharField(max_length=60, blank=True)
    back_extension = models.CharField(max_length=60, blank=True)
    ab_movement = models.CharField(max_length=60, blank=True)
    other = models.CharField(max_length=60, blank=True)
    notes = models.CharField(max_length=300, blank=True)
    media_url = models.URLField(blank=True)

tracker/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link href="https://fonts.googleapis.com/css?family=Catamaran|Passion+One" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	<title>Conjugate Tracker</title>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
	<script>
	        $(function() {
	                $( "#id_created_at" ).datepicker({
	                        dateFormat: "yy-mm-dd",
	                        defaultDate: "+1w",
	                        changeMonth: true,
	                        numberOfMonths: 2,
	                        onClose: function( selectedDate ) {
	                                $( "#id_created_at" ).datepicker( "option", selectedDate );
	                        }
	                });
	                var currentDate = new Date();
	                $('#id_created_at').val(currentDate.toISOString().split('T')[0]);
	        });
	</script>
</head>
<body>
<div class="container">
      <div class="masthead">
        <h3 class="text-muted">Conjugate Tracker</h3>
        <!--<nav>
          <ul class="nav nav-justified">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#">Projects</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Downloads</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
      </nav>-->
  </div>
	{% block content %}
	{% endblock %}
</div>
</body>
</html>

tracker/templates/edit_bench.html
{% extends 'tracker/base.html' %}
{% block content %}

<h1>Add a New Bench</h1>

<form action="{% url 'tracker:bench_edit' pk=pk  %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class="btn btn-1" />
</form>
{% endblock %}

tracker/templates/edit_deadlift.html
{% extends 'tracker/base.html' %}
{% block content %}

<h1>Add a New Deadlift</h1>
<form action="{% url 'tracker:deadlift_edit' pk=pk  %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class="btn btn-1"/>
</form>
{% endblock %}

tracker/templates/edit_lower.html
{% extends 'tracker/base.html' %}
{% block content %}

<h1>Add Lower Accessories</h1>

<form action="{% url 'tracker:lower_edit' pk=pk  %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class="btn btn-1"/>
</form>
{% endblock %}

tracker/templates/edit_squat.html
{% extends 'tracker/base.html' %}
{% block content %}


<h1>Add a New Squat</h1>
<form action="{% url 'tracker:squat_edit' pk=pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class= "btn btn-1" />
</form>

{% endblock %}

tracker/templates/edit_upper.html
{% extends 'tracker/base.html' %}
{% block content %}

<h1>Add Upper Accessories</h1>

<form action="{% url 'tracker:upper_edit' pk=pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class="btn btn-1"/>
</form>
{% endblock %}

tracker/templates/new_bench.html
{% extends 'tracker/base.html' %}
{% block content %}

<h1>Add a New Bench</h1>

<form action="{% url 'tracker:bench_new' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class="btn btn-1" />
</form>
{% endblock %}

tracker/templates/new_deadlift.html
{% extends 'tracker/base.html' %}
{% block content %}

<h1>Add a New Deadlift</h1>
<form action="{% url 'tracker:deadlift_new' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class="btn btn-1"/>
</form>
{% endblock %}

tracker/templates/new_lower.html
{% extends 'tracker/base.html' %}
{% block content %}


<h1>Add Lower Accessories</h1>

<select class="dropdown" id="LowAcc" onchange="ToggleEntry()">
  <option>Select all accessories</option>
  <option value="id_created_at">Workout Date</option>
  <option value="id_top_set">Top Set</option>
  <option value="id_ab_movement">Ab Movement</option>
  <option value="id_back_extension">Back Extension</option>
  <option value="id_belt_squat">Belt Squat</option>
  <option value="id_chair_dl">Chair Deadlift</option>
  <option value="id_dimel_dl">Dimel Deadlift</option>
  <option value="id_front_squat">Front Squat</option>
  <option value="id_ghr">Glute Ham Raise</option>
  <option value="id_good_morning">Good Morning</option>
  <option value="id_hack_squat">Hack Squat</option>
  <option value="id_hip_bridge">Hip Bridge</option>
  <option value="id_inverse_curl">Inverse Curl</option>
  <option value="id_kb_swings">Kettlebell Swings</option>
  <option value="id_leg_curl">Leg Curl</option>
  <option value="id_leg_press">Leg Press</option>
  <option value="id_lunge">Lunge</option>
  <option value="id_reverse_hyper">Reverse Hyper</option>
  <option value="id_step_up">Step Up</option>
  <option value="id_stiff_leg_dl">Stiff Leg Deadlift</option>
  <option value="id_trapbar_deadlift">Trapbar Deadlift</option>
  <option value="id_other">Other</option>
  <option value="id_notes">Notes</option>
</select>

<form action="{% url 'tracker:lower_new' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class="btn btn-1"/>
</form>

<script type="text/javascript">

window.onload = function() {
  HideList();
}

  function HideList() {
    var form = document.getElementsByTagName('form')[0];
    for (var i = 0; i < form.children.length - 1; i++) {

      form.children[i].style.display = 'none';
    }
}

function ToggleEntry() {
  var select = document.getElementById('LowAcc');
  var selectedId = select.options[select.selectedIndex].value;
  var targetElement = document.getElementById(selectedId);
  var parentElement = targetElement.parentElement;

  parentElement.style.display = 'block';

}

</script>
{% endblock %}

tracker/templates/new_squat.html
{% extends 'tracker/base.html' %}
{% block content %}


<h1>Add a New Squat</h1>
<form action="{% url 'tracker:squat_new' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class= "btn btn-1" />
</form>

{% endblock %}

tracker/templates/new_upper.html
{% extends 'tracker/base.html' %}
{% block content %}

<h1>Add Upper Accessories</h1>

<select class="dropdown" id="upAcc"  onchange="ToggleEntry()">
  <option>Select all accessories</option>
  <option value="id_created_at">Workout Date</option>
  <option value="id_top_set">Top Set</option>
  <option value="id_ab_movement">Ab Movement</option>
  <option value="id_bamboo_bar">Bamboo Bar</option>
  <option value="id_chest_supported_rows">Chest Supported Rows</option>
  <option value="id_close_grippness">Close Grip</option>
  <option value="id_db_press">DB Press</option>
  <option value="id_db_rollbacks">DB Rollbacks</option>
  <option value="id_db_rows">DB Rows</option>
  <option value="id_dead_press">Dead Press</option>
  <option value="id_dips">Dips</option>
  <option value="id_face_pulls">Face Pulls</option>
  <option value="id_inverted_row">Inverted Row</option>
  <option value="id_jam_press">JM Press</option>
  <option value="id_lat_pulldowns">Lat Pulldowns</option>
  <option value="id_lat_pullovers">Lat Pullovers</option>
  <option value="id_low_rows">Low Rows</option>
  <option value="id_olt_press">Overhead Press</option>
  <option value="id_pec_dec">Pec Dec</option>
  <option value="id_pullaparts">Pullaparts</option>
  <option value="id_pullups">Pullups</option>
  <option value="id_pushups">Pushups</option>
  <option value="id_rev_db_fly">Reverse DB Fly</option>
  <option value="id_reverse_pec_dec">Reverse Pec Dec</option>
  <option value="id_skull_crushers">Skull Crushers</option>
  <option value="id_tate_press">Tate Press</option>
  <option value="id_t_bar_rows">T Bar Rows</option>
  <option value="id_tri_extensions">Tricep Extensions</option>
  <option value="id_windmills">Windmills</option>
  <option value="id_other">Other</option>
  <option value="id_notes">Notes</option>
</select>

<form action="{% url 'tracker:upper_new' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class="btn btn-1"/>
</form>

<script type="text/javascript">

window.onload = function() {
  HideList();
}

  function HideList() {
    var form = document.getElementsByTagName('form')[0];
    for (var i = 0; i < form.children.length - 1; i++) {

      form.children[i].style.display = 'none';
    }
}

function ToggleEntry() {
  var select = document.getElementById('upAcc');
  var selectedId = select.options[select.selectedIndex].value;
  var targetElement = document.getElementById(selectedId);
  var parentElement = targetElement.parentElement;

  parentElement.style.display = 'block';

}

</script>
{% endblock %}

tracker/templates/signup.html
{% extends 'tracker/base.html' %}

{% block content %}
  <h2>Sign Up for Conjugate Tracker</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-1">Sign up</button>
  </form>
{% endblock %}