conjugate/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('tracker.urls')),
    url('^', include('django.contrib.auth.urls')),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
]

tracker/urls.py
from django.conf.urls import include, url
from django.http import HttpResponseRedirect, HttpResponse

from . import views
app_name = "tracker"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^accounts/',  include('registration.backends.hmac.urls')),
    url(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /",
                                                content_type="text/plain")),
    url(r'^squat_movement/(?P<pk>[0-9]+)/$',
        views.SquatDetailView.as_view(), name='squat_detail'),
    url(r'^deadlift_movement/(?P<pk>[0-9]+)/$',
        views.DeadliftDetailView.as_view(), name='deadlift_detail'),
    url(r'^bench_movement/(?P<pk>[0-9]+)/$',
        views.BenchDetailView.as_view(), name='bench_detail'),
    url(r'^lower_movement/(?P<pk>[0-9]+)/$',
        views.LowerDetailView.as_view(), name='lower_detail'),
    url(r'^upper_movement/(?P<pk>[0-9]+)/$',
        views.UpperDetailView.as_view(), name='upper_detail'),
    url(r'^squat_movement/new$', views.new_squat, name='squat_new'),
    url(r'^deadlift_movement/new$', views.new_deadlift, name='deadlift_new'),
    url(r'^bench_movement/new$', views.new_bench, name='bench_new'),
    url(r'^lower_movement/new$', views.new_lower, name='lower_new'),
    url(r'^upper_movement/new$', views.new_upper, name='upper_new'),
    url(r'^squat_movement/(?P<pk>\d+)/edit/$',
        views.squat_edit, name='squat_edit'),
    url(r'^bench_movement/(?P<pk>\d+)/edit/$',
        views.bench_edit, name='bench_edit'),
    url(r'^deadlift_movement/(?P<pk>\d+)/edit/$',
        views.deadlift_edit, name='deadlift_edit'),
    url(r'^upper_movement/(?P<pk>\d+)/edit/$',
        views.upper_edit, name='upper_edit'),
    url(r'^lower_movement/(?P<pk>\d+)/edit/$',
        views.lower_edit, name='lower_edit'),
    url(r'^squat_movement/search$', views.squat_search, name='squat_search'),
    url(r'^bench_movement/search$', views.bench_search, name='bench_search'),
    url(r'^deadlift_movement/search$',
        views.deadlift_search, name='deadlift_search'),
    url(r'^upper_movement/search$', views.upper_search, name='upper_search'),
    url(r'^lower_movement/search$', views.lower_search, name='lower_search'),
    url(r'^analysis$', views.analysis, name='analysis')
]

tracker/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class SquatMovement(models.Model):
    user = models.ForeignKey('auth.User')
    created_at = models.DateField(default=timezone.now, blank=True)
    effort_type = models.CharField(max_length=60)
    squat_notes = models.CharField(max_length=300, blank=True)
    box_free = models.CharField(max_length=60)
    bar_type = models.CharField(max_length=60, blank=True)
    bands_type = models.CharField(max_length=60, blank=True)
    reverse = models.BooleanField(default=False)
    chain_weight = models.IntegerField(default=0, blank=True)
    movement_weight = models.IntegerField(default=0)
    movement_sets = models.IntegerField(default=0)
    movement_reps = models.IntegerField(default=0)
    media_url = models.URLField(blank=True)


class DeadliftMovement(models.Model):
    user = models.ForeignKey('auth.User')
    created_at = models.DateField(default=timezone.now, blank=True)
    effort_type = models.CharField(max_length=60)
    sumo_conventional = models.CharField(max_length=60)
    deficit = models.BooleanField()
    block = models.BooleanField()
    standard = models.BooleanField()
    pin = models.BooleanField()
    reverse = models.BooleanField()
    bands_type = models.CharField(max_length=60, blank=True)
    chain_weight = models.IntegerField(blank=True)
    movement_weight = models.IntegerField(default=0)
    movement_sets = models.IntegerField(default=0)
    movement_reps = models.IntegerField(default=0)
    deadlift_notes = models.CharField(max_length=60, blank=True)
    media_url = models.URLField(blank=True)


class BenchMovement(models.Model):
    user = models.ForeignKey('auth.User')
    created_at = models.DateField(default=timezone.now, blank=True)
    effort_type = models.CharField(max_length=60)
    bar_type = models.CharField(max_length=60, blank=True)
    floor = models.BooleanField()
    reverse = models.BooleanField()
    board = models.IntegerField(blank=True, default=0)
    manpon = models.BooleanField()
    pin = models.BooleanField()
    bench_notes = models.CharField(max_length=60, blank=True)
    bands_type = models.CharField(max_length=60, blank=True)
    chain_weight = models.IntegerField(blank=True)
    movement_weight = models.IntegerField(default=0)
    movement_sets = models.IntegerField(default=0)
    movement_reps = models.IntegerField(default=0)
    media_url = models.URLField(blank=True)


class UpperAccessoryMovement(models.Model):
    user = models.ForeignKey('auth.User')
    created_at = models.DateField(default=timezone.now, blank=True)
    top_set = models.CharField(max_length=60, blank=True)
    close_grippness = models.CharField(max_length=60, blank=True)
    tate_press = models.CharField(max_length=60, blank=True)
    dips = models.CharField(max_length=60, blank=True)
    rev_db_fly = models.CharField(max_length=60, blank=True)
    windmills = models.CharField(max_length=60, blank=True)
    bamboo_bar = models.CharField(max_length=60, blank=True)
    lat_pulldowns = models.CharField(max_length=60, blank=True)
    lat_pullovers = models.CharField(max_length=60, blank=True)
    pec_dec = models.CharField(max_length=60, blank=True)
    reverse_pec_dec = models.CharField(max_length=60, blank=True)
    t_bar_rows = models.CharField(max_length=60, blank=True)
    chest_supported_rows = models.CharField(max_length=60, blank=True)
    low_rows = models.CharField(max_length=60, blank=True)
    pullups = models.CharField(max_length=60, blank=True)
    pushups = models.CharField(max_length=60, blank=True)
    inverted_row = models.CharField(max_length=60, blank=True)
    face_pulls = models.CharField(max_length=60, blank=True)
    db_rows = models.CharField(max_length=60, blank=True)
    db_press = models.CharField(max_length=60, blank=True)
    pullaparts = models.CharField(max_length=60, blank=True)
    tri_extensions = models.CharField(max_length=60, blank=True)
    skull_crushers = models.CharField(max_length=60, blank=True)
    jam_press = models.CharField(max_length=60, blank=True)
    olt_press = models.CharField(max_length=60, blank=True)
    db_rollbacks = models.CharField(max_length=60, blank=True)
    dead_press = models.CharField(max_length=60, blank=True)
    ab_movement = models.CharField(max_length=60, blank=True)
    other = models.CharField(max_length=60, blank=True)
    notes = models.CharField(max_length=300, blank=True)
    media_url = models.URLField(blank=True)


class LowerAccessoryMovement(models.Model):
    user = models.ForeignKey('auth.User')
    created_at = models.DateField(default=timezone.now, blank=True)
    top_set = models.CharField(max_length=60, blank=True)
    chair_dl = models.CharField(max_length=60, blank=True)
    ghr = models.CharField(max_length=60, blank=True)
    lunge = models.CharField(max_length=60, blank=True)
    dimel_dl = models.CharField(max_length=60, blank=True)
    reverse_hyper = models.CharField(max_length=60, blank=True)
    hip_bridge = models.CharField(max_length=60, blank=True)
    good_morning = models.CharField(max_length=60, blank=True)
    step_up = models.CharField(max_length=60, blank=True)
    belt_squat = models.CharField(max_length=60, blank=True)
    hack_squat = models.CharField(max_length=60, blank=True)
    leg_press = models.CharField(max_length=60, blank=True)
    leg_curl = models.CharField(max_length=60, blank=True)
    kb_swings = models.CharField(max_length=60, blank=True)
    trapbar_deadlift = models.CharField(max_length=60, blank=True)
    stiff_leg_dl = models.CharField(max_length=60, blank=True)
    inverse_curl = models.CharField(max_length=60, blank=True)
    front_squat = models.CharField(max_length=60, blank=True)
    back_extension = models.CharField(max_length=60, blank=True)
    ab_movement = models.CharField(max_length=60, blank=True)
    other = models.CharField(max_length=60, blank=True)
    notes = models.CharField(max_length=300, blank=True)
    media_url = models.URLField(blank=True)

tracker/templates/tracker/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

	<link href="https://fonts.googleapis.com/css?family=Catamaran|Passion+One" rel="stylesheet">
  <!-- <link href="{ static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"> -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<!-- Latest compiled and minified JavaScript -->
  <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
		<title>Conjugate Tracker</title>
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/logosmall.png' %}">

    <title>Narrow Jumbotron Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="jumbotron-narrow.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <script>
            $(function() {
                    $( "#id_created_at" ).datepicker({
                            dateFormat: "yy-mm-dd",
                            defaultDate: "+1w",
                            changeMonth: true,
                            numberOfMonths: 2,
                            onClose: function( selectedDate ) {
                                    $( "#id_created_at" ).datepicker( "option", selectedDate );
                            }
                    });
                    var currentDate = new Date();
                    var offset = currentDate.getTimezoneOffset() * 60000;
                    $('#id_created_at').val((new Date(Date.now() - offset)).toISOString().split('T')[0]); 
            });
    </script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-26468095-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-26468095-2');
    </script>

  </head>

  <body>
<div class="bodyimage">
    <div class="container">
      <div class="header clearfix">
        <nav role="navigation">
        <a href="/"><div class="logo"></div></a>
          <a data-toggle="collapse" data-target="#header-menu" href="#header-menu">
            <div type="button" class="hamburger_icon collapsed">
            </div>
          </a>
          <ul class="header_menu collapse" id="header-menu">
            <li type="button" role="presentation" class="active header_item bordered_list"><a class="default_link" href="/">Home for {{user_name.title}}</a></li>
            <li type="button" role="presentation" class="active header_item bordered_list">
              <a class="default_link" href="#collapse1" data-toggle="collapse" data-target="#header-menu-log">Log New Movement</a>
              <ul class="collapse" id="header-menu-log">
                <li type="button" role="presentation" class="active header_item bordered_list"><a class="default_link" href="{% url 'tracker:squat_new' %}">Add New Squat</a></li>
                <li type="button" role="presentation" class="active header_item bordered_list"><a class="default_link" href="{% url 'tracker:bench_new' %}">Add New Bench</a></li>
                <li type="button" role="presentation" class="active header_item bordered_list"><a class="default_link" href="{% url 'tracker:deadlift_new' %}">Add New Deadlift</a></li>
                <li type="button" role="presentation" class="active header_item bordered_list"><a class="default_link" href="{% url 'tracker:upper_new' %}">Add New Upper Accessory</a></li>
                <li type="button" role="presentation" class="active header_item bordered_list"><a class="default_link" href="{% url 'tracker:lower_new' %}">Add New Lower Accessory</a></li>
              </ul>
            </li>
            <li type="button" role="presentation" class="active header_item bordered_list">
              <a class="default_link" href="#collapse1" data-toggle="collapse" data-target="#header-menu-search">Search Movements</a>
              <ul class="collapse" id="header-menu-search">
                <li type="button" role="presentation" class="active header_item bordered_list"><a class="default_link" href="{% url 'tracker:squat_search' %}">Search for Squat</a></li>
                <li type="button" role="presentation" class="active header_item bordered_list"><a class="default_link" href="{% url 'tracker:bench_search' %}">Search for Bench</a></li>
                <li type="button" role="presentation" class="active header_item bordered_list"><a class="default_link" href="{% url 'tracker:deadlift_search' %}">Search for Deadlift</a></li>
                <li type="button" role="presentation" class="active header_item bordered_list"><a class="default_link" href="{% url 'tracker:upper_search' %}">Search Upper Accessories</a></li>
                <li type="button" role="presentation" class="active header_item bordered_list"><a class="default_link" href="{% url 'tracker:lower_search' %}">Search Lower Accessories</a></li>
              </ul>
            </li>
                <li type="button" role="presentation" class="active header_item bordered_list"><a class="default_link" href="{% url 'tracker:analysis' %}">Analysis</a></li>
            <li type="button" role="presentation" class="header_item bordered_list"><a class="default_link" href="mailto:admin@conjugatetracker.com">Email Admin</a></li>
            <li type="button" role="presentation" class="header_item bordered_list"><a class="default_link" href="/accounts/logout">Sign Out</a></li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
		{% block content %}
		{% endblock %}

		      <!--<footer class="footer">
		        <!<p>&copy; 2017 Conjugate Tracker</p>
		      </footer>-->
</body>
</html>

tracker/templates/tracker/benchmovement_search.html
{% extends 'tracker/base.html' %}
{% block content %}
<div class="page_format">
<h3>Search Bench Movements</h3>
<form action="{% url 'tracker:bench_search' %}" method="get">
    <p><label for="id_effort_type_0">Day:</label> <ul id="id_effort_type"><li><label for="id_effort_type_0"><input id="id_effort_type_0" name="effort_type" type="radio" value="Dynamic" /> Dynamic Effort</label></li>
<li><label for="id_effort_type_1"><input id="id_effort_type_1" name="effort_type" type="radio" value="Max" /> Max Effort</label></li></ul></p>
<p><label for="id_bar_type">Bar Type:</label> <select id="id_bar_type" name="bar_type">
<option value=""></option>
<option value="Straight">Straight</option>
<option value="Cambered">Cambered</option>
<option value="Bow">Bow</option>
<option value="Football Bar">Football Bar</option>
</select></p>
<p><label for="id_floor">Floor Press:</label> <input id="id_floor" name="floor" type="checkbox" value="True"/></p>
<p><label for="id_reverse">Reverse Band:</label> <input id="id_reverse" name="reverse" type="checkbox" value="True"/></p>
<p><label for="id_board">Board:</label><select id="id_board" name="board">
  <option value=""></option>
  <option value="0">None</option>
  <option value="1">1</option>
  <option value="2">2</option>
  <option value="3">3</option>
  <option value="4">4</option>
  </select></p>

<p><label for="id_manpon">Manpon:</label> <input id="id_manpon" name="manpon" type="checkbox" value="True"/></p>
<p><label for="id_pin">Pin:</label> <input id="id_pin" name="pin" type="checkbox" value="True"/></p>
<p><label for="id_bands_type">Band Type:</label> <select id="id_bands_type" name="bands_type">
<option value=""></option>
<option value="None">None</option>
<option value="Micro mini">Micro Mini</option>
<option value="Mini">Mini</option>
<<option value="Monster Mini">Monster Mini</option>
<option value="Light">Light</option>
<option value="Average">Average</option>
<option value="Heavy">Heavy</option>
</select></p>
<p><label for="id_chain_weight">Chain weight:</label> <input id="id_chain_weight" name="chain_weight" type="number" /></p>
<p><label for="id_movement_weight">Bar Weight:</label> <input class="form-control" id="id_movement_weight" name="movement_weight" placeholder="Example: 150" type="number"  /></p>
<p><label for="id_movement_sets">Sets:</label> <input class="form-control" id="id_movement_sets" name="movement_sets" placeholder="Example: 1" type="number" /></p>
<p><label for="id_movement_reps">Reps:</label> <input class="form-control" id="id_movement_reps" name="movement_reps" placeholder="Example: 1" type="number" /></p>
<p><label for="id_bench_notes">Bench notes:</label> <input class="form-control" id="id_bench_notes" maxlength="300" name="bench_notes" placeholder="Add Bench Notes Here" type="text" /></p>
<p><label for="id_media_url">Media url:</label> <input class="form-control" id="id_media_url" name="media_url" placeholder="Add Media URL Here" type="text" /></p>
    <input type="submit" value="Search" class="btn btn-1" />
</form>

{% if not objects %}
<h2> No Results. Please search again..</h2>
{% else %}
<h2>Results</h2>
{% endif %}

{% for object in objects %}
<h3>
    - <a class="default_link "href="{% url 'tracker:bench_detail' object.id %}">{{ object.bar_type }} Bar Bench on {{ object.created_at }}, ({{object.effort_type}} Effort, Weight:{{object.movement_weight}})</a>
</h3>
{% endfor %}
</div>

{% endblock %}

tracker/templates/tracker/index.html
{% extends 'tracker/base.html' %}
{% block content %}

      <!-- The justified navigation menu is meant for single line per list item.
      Multiple lines will require custom code not provided by Bootstrap. -->
      <div class="row marketing">
        <div class="col-lg-6">
          <h3><b>Squat Movements</b></h3>
          {% if latest_squat_list %}
          <ul>
              {% for squat in latest_squat_list %}
              <li class="bordered_list"><a class="default_link" href="{% url 'tracker:squat_detail' squat.id %}">{{ squat.bar_type }} Bar, {{ squat.effort_type }} Effort</a></li>
              {% endfor %}
          </ul>
          {% else %}
          <p>No squats recorded. Shame.</p>
          {% endif %}

          <p><a class="btn btn-1" href="{% url 'tracker:squat_new' %}" role="button">Add New &raquo;</a>
              <a class="btn btn-2" href="{% url 'tracker:squat_search' %}" role="button">Search Squats &raquo;</a></p>

          <h3><b>Bench Movements</b></h3>
          {% if latest_bench_list %}
          <ul>
              {% for bench in latest_bench_list %}
              <li class="bordered_list"><a class="default_link" href="{% url 'tracker:bench_detail' bench.id %}">{{ bench.bar_type }} Bar, {{ bench.effort_type}} Effort</a></li>
              {% endfor %}
          </ul>
          {% else %}
          <p>No benchs recorded. Shame.</p>
          {% endif %}
          <p><a class="btn btn-1" href="{% url 'tracker:bench_new' %}" role="button">Add New &raquo;</a>
          <a class="btn btn-2" href="{% url 'tracker:bench_search' %}" role="button">Search Bench &raquo;</a></p>

        </div>

        <div class="col-lg-6">
          <h3><b>Deadlift Movements</b></h3>
          {% if latest_deadlift_list %}
          <ul>
              {% for deadlift in latest_deadlift_list %}
              <li class="bordered_list"><a class="default_link" href="{% url 'tracker:deadlift_detail' deadlift.id %}">Deadlift, {{ deadlift.effort_type}} Effort, {{ deadlift.sumo_conventional}}</a></li>
              {% endfor %}
          </ul>
          {% else %}
          <p>No deadlifts recorded. Really?</p>
          {% endif %}


          <p><a class="btn btn-1" href="{% url 'tracker:deadlift_new' %}" role="button">Add New &raquo;</a>
          <a class="btn btn-2" href="{% url 'tracker:deadlift_search' %}" role="button">Search Deadlift &raquo;</a></p>

          <h3><b>Lower Accessory Movements</b></h3>
          {% if latest_loweraccessory_list %}
          <ul>
              {% for loweraccessory in latest_loweraccessory_list %}
              <li class="bordered_list"><a class="default_link" href="{% url 'tracker:lower_detail' loweraccessory.id %}">Lower Accessory Movements</a></li>
              {% endfor %}
          </ul>
          {% else %}
          <p>No lower accessories recorded. Shame.</p>
          {% endif %}

          <p><a class="btn btn-1" href="{% url 'tracker:lower_new' %}" role="button">Add New  &raquo;</a></p>
          <a class="btn btn-2" href="{% url 'tracker:lower_search' %}" role="button">Search Lower Accessory &raquo;</a></p>

          <h3><b>Upper Accessory Movements</b></h3>
          {% if latest_upperaccessory_list %}
          <ul>
              {% for upperaccessory in latest_upperaccessory_list %}
              <li class="bordered_list"><a class="default_link" href="{% url 'tracker:upper_detail' upperaccessory.id %}">Upper Accessory Movements</a></li>
              {% endfor %}
          </ul>
          {% else %}
          <p>No upper accessories recorded. Shame.</p>
          {% endif %}

          <p><a class="btn btn-1" href="{% url 'tracker:upper_new' %}" role="button">Add New</a></p>
          <a class="btn btn-2" href="{% url 'tracker:upper_search' %}" role="button">Search Upper Accessory&raquo;</a></p>
        </div>
      </div>

 <!-- /container -->




{% endblock %}

tracker/templates/tracker/squatmovement_search.html
{% extends 'tracker/base.html' %}
{% block content %}
<h3>Search Squat Movements</h3>
<form action="{% url 'tracker:squat_search' %}" method="get">
    <p><label for="id_box_free_0">Squat Type:</label> <ul id="id_box_free"><li><label for="id_box_free_0"><input id="id_box_free_0" name="box_free" type="radio" value="Free" /> Free</label></li>
<li><label for="id_box_free_1"><input id="id_box_free_1" name="box_free" type="radio" value="Box" /> Box</label></li></ul></p>
<p><label for="id_effort_type_0">Day:</label> <ul id="id_effort_type"><li><label for="id_effort_type_0"><input id="id_effort_type_0" name="effort_type" type="radio" value="Dynamic"  /> Dynamic Effort</label></li>
<li><label for="id_effort_type_1"><input id="id_effort_type_1" name="effort_type" type="radio" value="Max"  /> Max Effort</label></li></ul></p>
<p><label for="id_bar_type">Bar Type:</label> <select id="id_bar_type" name="bar_type" >
<option value=""></option>
<option value="Straight">Straight</option>
<option value="Giant Cambered">Giant Cambered</option>
<option value="Buffalo">Buffalo</option>
<option value="Bow">Bow</option>
<option value="Safety Squat Bar">Safety Squat Bar</option>
</select></p>
<p><label for="id_bands_type">Band Type:</label> <select id="id_bands_type" name="bands_type">
<option value=""></option>
<option value="None">None</option>
<option value="Micro mini">Micro Mini</option>
<option value="Mini">Mini</option>
<<option value="Monster Mini">Monster Mini</option>
<option value="Light">Light</option>
<option value="Average">Average</option>
<option value="Heavy">Heavy</option>
</select></p>
<p><label for="id_reverse">Reverse Band:</label> <input id="id_reverse" name="reverse" type="checkbox" value="True"/></p>
<p><label for="id_chain_weight">Chain weight:</label> <input id="id_chain_weight" name="chain_weight" type="number" /></p>
<p><label for="id_movement_weight">Bar Weight:</label> <input class="form-control" id="id_movement_weight" name="movement_weight" placeholder="Example: 150" type="number"  /></p>
<p><label for="id_movement_sets">Sets:</label> <input class="form-control" id="id_movement_sets" name="movement_sets" placeholder="Example: 1" type="number" /></p>
<p><label for="id_movement_reps">Reps:</label> <input class="form-control" id="id_movement_reps" name="movement_reps" placeholder="Example: 1" type="number"  /></p>
<p><label for="id_squat_notes">Squat notes:</label> <input class="form-control" id="id_squat_notes" maxlength="300" name="squat_notes" placeholder="Add Squat Notes Here" type="text" /></p>
<p><label for="id_media_url">Media url:</label> <input class="form-control" id="id_media_url" name="media_url" placeholder="Add Media URL Here" type="text" /></p>
    <input type="submit" value="Search" class= "btn btn-1" />
</form>
{% if not objects %}
<h2> No Results. Please search again..</h2>
{% else %}
<h2>Results</h2>
{% endif %}

{% for object in objects %}
<h3>
    - <a class="default_link" href="{% url 'tracker:squat_detail' object.id %}">{{ object.bar_type }} Bar Squat on {{ object.created_at }}, ({{object.effort_type}} Effort, Weight:{{object.movement_weight}})</a>
</h3>
{% endfor %}

{% endblock %}